</$objtype/mkfile

TARG=ja

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../jc/j.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

BIN=/$objtype/bin

< /sys/src/cmd/mkone
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
