</$objtype/mkfile

TARG=jl

OFILES=\
	asm.$O\
	compress.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../jc/j.out.h\

BIN=/$objtype/bin
CFLAGS=$CFLAGS -. -I.
</sys/src/cmd/mkone

enam.$O:	../jc/enam.c
	$CC $CFLAGS ../jc/enam.c
