</$objtype/mkfile

TARG=jc
OFILES=\
	cgen.$O\
	enam.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	lex.$O\

HFILES=\
	gc.h\
	j.out.h\
	../cc/compat.h\
	../cc/cc.h\

T=j
<../cc/mkfile.port
</sys/src/cmd/mkone

lex.$O: ../cc/lex.c ../cc/y.tab.h
	$CC -Dmain'='ccmain $CFLAGS ../cc/lex.c
